### PR TITLE
fix(lint): do not output warning about react on non-react projects

### LINKED ISSUE #279: Option to opt-out of eslint-plugin-react
### Current Behavior

`tsdx` supports `eslint-plugin-react` outof the box. If React is not used this warning pops up: 
```
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
```

### Desired Behavior

Opt-out of `eslint` plugins that are not in used. For example, I'm using `tsdx` to build a logger plugin for a specific library. I don't need `.eslintrc` extending`react-app`, because my work is only `node` related. 

### Suggested Solution

My suggestion is to remove any dedicated `eslint` plugin except the ones that are `typescript` and `prettier` related. User would manually add additional rules to the project if needed, for example `eslint-plugin-vue`, and configure it in the local `.eslintrc`.  This way `tsdx` remains decoupled from any specific library.

### Who does this impact? Who is this for?

TypeScript users that develop plugins, libraries for NodeJS.

### PR DESCRIPTION
**Pull request by arthurdenner**
**Current behavior:**
We get a warning about detecting React version using the `lint` command in non-react projects.

**New behavior:**
Using the shared settings and the same value used by `eslint-plugin-react` [internally](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/version.js#L29) - it could be almost any value, but I chose this one, we don't get the warning on non-react projects. Closes #279.

**How to reproduce:**
- Use `tsdx lint` inside a react and a non-react project;
- No warning is displayed on both cases.

**Notes:**
N/A.

### CODE REVIEW

**Comment by sw-yx** [comment]
looks good enough. ready to merge?

**Comment by arthurdenner** [comment]
@sw-yx, I believe so. :smiley:

**Comment by sw-yx** [comment]
thanks for the great pr! will go out with the next release

**Comment by pcowgill** [comment]
Would you consider shipping a tiny patch release with this change? Or have some bigger changes already made it into master that make that tricky? Not a big deal either way, of course - just curious. Thanks!

**Comment by sw-yx** [comment]
its up to @jaredpalmer - he controls the releases

**Comment by EthianWong** [comment]
When to push this change to npm？i think i need it. @jaredpalmer

**Comment by sw-yx** [comment]
thanks for the great PR! @all-contributors please add @arthurdenner for bugs, code

**Comment by pcowgill** [comment]
Do you know if this change has been released yet? Thanks!

**Comment by arthurdenner** [comment]
@pcowgill, yes, it was released on [`v0.12.0`](https://github.com/jaredpalmer/tsdx/releases/tag/v0.12.0).

**Pull request merged**
