### PR TITLE
Rollback #208: Reinstate `rollup-plugin-typescript2` 

### LINKED ISSUE #268: No .d.ts created after update to 0.10.0
### Current Behavior

//index.ts
import { PrivateRoute, PublicRoute } from "./components";

export {
    PrivateRoute,
    PublicRoute
}
will generate 
//index.d.ts
/// <reference types="react" />
export { PrivateRoute, PublicRoute };
and directories of components with .d.ts arent created
[ss](https://i.imgur.com/2W6kqxM.png)

### Expected behavior

In 0.9.3 the .d.ts are created:
[ss](https://i.imgur.com/RfeuOHv.png)
//index.d.ts
import { PrivateRoute, PublicRoute } from "./components";
export { PrivateRoute, PublicRoute };

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | >=0.10.0
| TypeScript       | ^3.6.4
| Browser          | 
| npm/Yarn         | v1.17.3
| Operating System | Arch

### PR DESCRIPTION
**Pull request by medelman17**
As described in #200, `tsdx` previously utilized `rollup-plugin-typescript2` to compile and check TypeScript files. On account of the fact that the above plugin cannot be used alongside other rollup plugins that contain async/await syntax without a workaround, `tsdx` migrated to `@wessberg/rollup-plugin-ts` in #208. However, as discussed in #268, #274, #285 and elsewhere, the above migration caused untoward consequences in certain instances for existing `tsdx` users with custom `babel` setups. 

This PR reverts support `@wessberg/rollup-plugin-ts` and restores `rollup-plugin-typescript2` as compiler in chief. 

Closes #268, #274, #285

### CODE REVIEW

**Comment by markerikson** [comment]
Hmm.  We specifically updated Redux Starter Kit to use 0.10.6 because it started correctly merging all our declarations into a single `index.d.ts` file, vs a separate `.d.ts` file per source file.  Does this rollback still do things as a single `index.d.ts` file?

**Comment by jaredpalmer** [comment]
Yes, I believe so. The issue was that the rollup-plugin-ts2 really did not work as advertised and introduced more problematic and inconsistent bugs such as duplicative references directives and incorrect declarations. @markerikson why does merging declarations matter?

**Comment by markerikson** [comment]
I know @phryneas pointed out some issues where that might not work with certain Webpack setups, apparently.  See https://github.com/reduxjs/redux-starter-kit/pull/212#issuecomment-543033641 for discussion.

**Comment by jaredpalmer** [comment]
@medelman17 @markerikson FWIW, my OG formik rollup setup (pre-tsdx) didn't use `rollup-plugin-typescript2` at all, instead it did a 2 pass compile. First pass used `tsc-watch` (which is just `tsc` with an `onSuccess` flag) to compile typescript to a temp directory. Second pass just used rollup to bundle that JS up and move the types to the dist dir. The clear benefit of this setup is that you can just use good ol' `tsc` and let it do it's thing. Then you can let people go buck wild with rollup.

**Comment by wessberg** [comment]
> Yes, I believe so. The issue was that the rollup-plugin-ts2 really did not work as advertised and introduced more problematic and inconsistent bugs such as duplicative references directives and incorrect declarations.

Merging declarations, something that rollup-plugin-typescript2 doesnt do, is non-trivial. I think it's a bit harsh to right out say it is not working as advertised 🙂. I'm putting a lot of effort into fixing whatever issues that remains with declaration bundling and are addressing the issues one at a time.

**Comment by jaredpalmer** [comment]
Didn't mean to come off as rude, nor does this have anything to do with lack of effort. I understand that you're working through bugs, but until those are fixed, we need to ensure that the published version of tsdx still works in the interim. Looking forward to when the declaration merging is stuff is sorted out. It's very cool and exciting.

**Comment by tunnckoCore** [comment]
I was betting it will conflict. :laughing: The customBabelRollup plugin should be removed (entirely dropping `rollup-plugin-babel`) and passed as babelConfig to the `ts` plugin, I believe. But yea, I agree that we need to wait :)

**Comment by markerikson** [comment]
@jaredpalmer : no, it looks like v0.11.0 is _not_ combining types into a single `index.d.ts` file.

I just tried updating Redux Starter Kit and rebuilding, and it's back to individual `.d.ts` files per source file.

**Comment by smashercosmo** [comment]
hm... so, what's the recommended approach then to introduce additional rollup plugins that contain async/await?

**Pull request merged**
