### PR TITLE
Add back support for node 8

### PR DESCRIPTION
**Pull request by jaredpalmer**
Thank you @wessberg for the help

### CODE REVIEW

**Comment by jaredpalmer** [comment]
@wessberg need you bump version of browserlist generator in rollup-plugin-ts and then publish .69

**Comment by wessberg** [comment]
I've already bumped the dependency and published a new version, so we should be good 😊

**Comment by jaredpalmer** [comment]
@wessberg Still failing: https://github.com/jaredpalmer/tsdx/runs/260960301#step:5:7

**Comment by wessberg** [comment]
Ah, didn't change the engine property from >=9.00 to >= 8 inside of browserslist-generator before publish. I'll get a new version published later today and will update here when it's done.

**Comment by wessberg** [comment]
Fixed in v1.1.69!

**Comment by wessberg** [comment]
I see that you're having the issue with another one of my packages on the CI pipeline. Let me fix that one too.

**Comment by jaredpalmer** [comment]
@wessberg https://github.com/jaredpalmer/tsdx/pull/250/checks?check_run_id=261186208#step:5:7

**Comment by wessberg** [comment]
[Fixed](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.70)

**Pull request merged**
