### PR TITLE
Replaced some sync methods for their async version

### PR DESCRIPTION
**Pull request by gndelia**
See #265 

I removed most of the sync functions, there are some scenarios which I am unsure what to do. For instance, those sync calls that are at module level (like `src/index.ts` line 50 or line 60)

Same for `src/errors/transformErrorMessages.ts` - I am unsure if I can make that function async

Still pending one change from `getProjectPath()` in `src/index.ts`

### CODE REVIEW

**Comment by gndelia** [comment]
There are some options I was unable to migrate - I think it's not possible. Like the following https://github.com/jaredpalmer/tsdx/blob/master/src/index.ts#L50 and a couple more that are code part of a module and therefore can't be async (that's my understanding)

**Comment by sw-yx** [comment]
mm i think we had some merge conflicts from other PRs. if you have time to address them, be my guest, if not i'll try to update when i free up

**Comment by gndelia** [comment]
@sw-yx  I rebased and solve the conflicts :)

**Comment by sw-yx** [comment]
Thank you!

**Comment by agilgur5** [comment]
@all-contributors please add @gndelia for code

**Pull request merged**
