### PR TITLE
Added Storybook template

### PR DESCRIPTION
**Pull request by Carl-Foster**
I gave this library a try to setup a design-library to be built with Storybook. Found it was more cumbersome than I thought but got it setup and felt it worthwhile to add a template here.
To enable further templates, I refactored how the template configs are defined but I'm not super happy with my implementation. Open to how that could be improved.
All feedback welcome

### CODE REVIEW

**Comment by Carl-Foster** [comment]
@jaredpalmer is this PR fair enough? I'm happy to adjust it as I really appreciate this project.

**Comment by jaredpalmer** [comment]
@swyx? What u think? I’m fine with it?

**Comment by sw-yx** [comment]
yup! fine with it too

**Comment by sw-yx** [comment]
@Carl-Foster mind adding the docs addon by default? its something i really want to encourage everyone uses

**Comment by Carl-Foster** [comment]
> @Carl-Foster mind adding the docs addon by default? its something i really want to encourage everyone uses

Sorry don't really understand what you mean by this.

**Comment by sw-yx** [comment]
[storybook addon docs](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf) is one of their biggest new things

**Comment by Carl-Foster** [comment]
I unfortunately couldn't get the docs addon to work with Typescript seamlessly. I think if someone starts using the template can get it to work, then they can add it later.

**Comment by sw-yx** [comment]
cool! thanks v much!

**Comment by sw-yx** [comment]
thanks for the great PR! @all-contributors please add @Carl-Foster for ideas, docs, code, tests

**Pull request merged**
