### PR TITLE
Pass tests in cases where no tests exist

### PR DESCRIPTION
**Pull request by sadsa**

### CODE REVIEW

**Comment by sw-yx** [comment]
would you apply this flag to the non react test commands as well?

**Comment by sadsa** [comment]
My answer is Yes but I guess this question is more "Should the test script pass in the absence of tests?". Personally, I found it strange `tsdx test` threw an error because it couldn't find any valid tests. I would expect that it said "I couldn't find any tests to run, oh well, lets move on"

**Comment by sw-yx** [comment]
ok. no strong feelings on this one

**Comment by agilgur5** [comment]
@allcontributors please add @sadsa for code

**Pull request merged**
