### PR TITLE
Custom templates

### PR DESCRIPTION
**Pull request by MerrickGit**
#441

Added option `--custom-template`.

usage `tsdx create app_name --custom-template ~/Desktop/templates/my_template`

One important thing is `template.json` inside the template folder.

If this method is satisfies the reviewers, then I will add documentation and checking for `template.json` file.

### CODE REVIEW

**Comment by sw-yx** [comment]
hmm it might be more common to host templates on github rather than your filesystem - what do you think

**Comment by jaredpalmer** [comment]
It should be remote, via GitHub

**Comment by MerrickGit** [comment]
I think it will be next feature because we need a logic to work with templates in the file system. I can leave only remote or can add the following PR —remote-template option

**Comment by MerrickGit** [comment]
> It should be remote, via GitHub

**Comment by jaredpalmer** [comment]
Imho all templates should be remote

**Comment by MerrickGit** [comment]
> Imho all templates should be remote

May be via npm, not all companies use github?

**Comment by kdubb1337** [comment]
We're using TSDX pretty heavily on a monorepo, and it causes you to make the same series of changes each time. I think custom templates is a much better option than forking. Can we reopen this PR?

**Comment by luistak** [comment]
@kdubb1337 same problem in here

**Pull request closed without merging**
